// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-cotacoes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_cotacoes_default = defineTool({
  name: "list_cotacoes",
  title: "Listar cota\xE7\xF5es",
  description: "Lista as cota\xE7\xF5es (listas) do usu\xE1rio autenticado. Filtra opcionalmente por status.",
  inputSchema: {
    status: z.enum(["aberta", "finalizada"]).optional().describe("Filtrar por status."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb(ctx).from("listas").select("id,nome,status,created_at,produtos").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      nome: r.nome,
      status: r.status,
      created_at: r.created_at,
      produtos_count: Array.isArray(r.produtos) ? r.produtos.length : 0
    }));
    return { content: [{ type: "text", text: JSON.stringify(rows) }], structuredContent: { rows } };
  }
});

// src/lib/mcp/tools/get-cotacao.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_cotacao_default = defineTool2({
  name: "get_cotacao",
  title: "Detalhar cota\xE7\xE3o",
  description: "Retorna detalhes de uma cota\xE7\xE3o do usu\xE1rio autenticado, incluindo produtos.",
  inputSchema: { id: z2.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb2(ctx).from("listas").select("*").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Cota\xE7\xE3o n\xE3o encontrada" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { cotacao: data } };
  }
});

// src/lib/mcp/tools/list-fornecedores.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_fornecedores_default = defineTool3({
  name: "list_fornecedores",
  title: "Listar fornecedores",
  description: "Lista os fornecedores cadastrados pelo usu\xE1rio autenticado.",
  inputSchema: {
    estado: z3.enum(["MT", "GO"]).optional(),
    limit: z3.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb3(ctx).from("fornecedores").select(
      "id,nome,nome_representante,whatsapp,email,codigo_estado,codigo_interno_ciss_mt,codigo_interno_ciss_go,codigo_interno_consinco_mt,codigo_interno_consinco_go"
    ).eq("user_id", ctx.getUserId()).limit(limit);
    if (estado) q = q.eq("codigo_estado", estado);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-respostas.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_respostas_default = defineTool4({
  name: "list_respostas",
  title: "Listar respostas de fornecedores",
  description: "Lista as respostas de fornecedores para uma cota\xE7\xE3o do usu\xE1rio autenticado.",
  inputSchema: { lista_id: z4.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lista_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb4(ctx).from("respostas").select("id,empresa,resposta,created_at").eq("user_id", ctx.getUserId()).eq("lista_id", lista_id).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }], structuredContent: { rows: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ljlhrkzowsbjkqzdvrrw";
var mcp_default = defineMcp({
  name: "cotacoes-nilo-mcp",
  title: "COTARME MCP",
  version: "0.1.0",
  instructions: "Ferramentas de leitura para o sistema COTARME. Use `list_cotacoes` para ver cota\xE7\xF5es do usu\xE1rio, `get_cotacao` para detalhes de uma cota\xE7\xE3o, `list_fornecedores` para os fornecedores cadastrados e `list_respostas` para respostas de fornecedores a uma cota\xE7\xE3o. Todos os dados s\xE3o escopados ao usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_cotacoes_default, get_cotacao_default, list_fornecedores_default, list_respostas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
